// <auto-generated />
using System;
using BrockLee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrockLee.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrockLee.Models.Entities.UserLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExpenseCount")
                        .HasColumnType("int");

                    b.Property<decimal>("IndexRealValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NpsRealValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("ResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<decimal>("TaxBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRemanent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearsToRetirement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoggedAt")
                        .IsDescending();

                    b.ToTable("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
